### ISSUE TITLE
Can you provide "VERSION" file?

### ISSUE THREAD

**Issue by bpilseo** [XPixelGroup/RethinkVSRAlignment#1]
Traceback (most recent call last):
  File "setup.py", line 83, in <module>
    write_version_py()
  File "setup.py", line 60, in write_version_py
    with open('VERSION', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'

**Comment by Shuweis** [comment]
I have provided this file. You can try it for free.
